version: '2'

services:
  edge-router:
    image: weaveworksdemos/edge-router:0.1.1
    ports:
      - '80:80'
    hostname: edge-router
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    hostname: front-end
  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
